version: '3.4'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "7777:7777" 
    environment:
      - ISCONTAINER=true
  #storage:
  #  build: 
  #    context: .
  #    dockerfile: Dockerfile.storage
  #  ports:
  #    - "8888:8888" 
