version: '3.4'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "7777:7777" 
#  k6:
#    image: loadimpact/k6:latest
#    command: run /test.js
#    volumes:
#      - ./test.js:/test.js